## Numpy 

In [2]:
import numpy as np

### Creating Arrays

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [15]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = int)
print(b, '\n')
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
print(b)

[[1 2 3]
 [4 5 6]] 

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [17]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
 dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

## Initial Placeholders

In [22]:
np.zeros((3,4)) # Creates an array of zeros with 3 rows and 4 cols 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((5,3,4), dtype=np.int16) # Create an array of ones with five batches

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [37]:
np.arange(10) # Creates an array of evenly spaced values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(0, 10, 2) # Create an array with 0 to 10 with step 2

array([0, 2, 4, 6, 8])

In [43]:
random_arr = np.random.rand(3,3) # Creates an array of random values bw 0 and 1
random_arr

array([[0.57154018, 0.33893571, 0.51580685],
       [0.54804861, 0.85189646, 0.0197984 ],
       [0.44811626, 0.64675285, 0.83098652]])

In [46]:
linspace = np.linspace(0, 1, 5) # 5 evenly spaced numbers from 0 to 1
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

###  Array Dimensions

In [48]:
random_arr.shape # array dimensions

(3, 3)

In [50]:
random_arr.dtype # data type

dtype('float64')

In [53]:
random_arr.size # total number of elements

9

In [55]:
random_arr.ndim # number of dimensions

2

### Array Operations

In [63]:
arr = np.array([(1,2,3), (4,5,6)], dtype = int)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr = arr + 2
print(arr, '\n')

arr = arr * 3
print(arr)

[[3 4 5]
 [6 7 8]] 

[[ 9 12 15]
 [18 21 24]]


In [65]:
arr1 = np.array([(1,2,3), (4,5,6)], dtype = int)
arr2 = np.array([(1,2,3), (4,5,6)], dtype = int)

In [67]:
arr1 + arr2 # Element wise addition

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [69]:
arr1 * arr2 # Element wise multiplication

array([[ 1,  4,  9],
       [16, 25, 36]])

In [78]:
arr3 = np.array([(1,2,3), (4,5,6), (7, 8, 9)], dtype = int)
np.dot(arr1, arr3) # matrix multplication or dot product

array([[30, 36, 42],
       [66, 81, 96]])

In [80]:
arr1.sum()

21

In [81]:
arr1.mean()

3.5

In [82]:
arr1.std()

1.707825127659933

In [83]:
arr.min()

9

In [84]:
arr.max()

24

### Reshaping and Transposing

In [86]:
arr1.reshape(3,2) # Reshape array to 3*2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
arr1.T # Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
arr1.ravel() # Flatten array

array([1, 2, 3, 4, 5, 6])

### Indexing and Slicing 

In [106]:
arr = np.array([(1.5,2,3), (4,5,6), (3,2,1), (4,5,6)],
 dtype = int)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [4, 5, 6]])

In [110]:
arr[1:3] # Slice from index 1 to 2

array([[4, 5, 6],
       [3, 2, 1]])

In [113]:
arr[1:4:2] # Slice with step 2 or odd elements

array([[4, 5, 6],
       [4, 5, 6]])

In [115]:
arr[0:4:2] # Slice with step 2 or even elements

array([[1, 2, 3],
       [3, 2, 1]])

In [117]:
arr[::-1] # reverse array

array([[4, 5, 6],
       [3, 2, 1],
       [4, 5, 6],
       [1, 2, 3]])

In [127]:
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [129]:
array1 = np.array([[1, 3, 5, 7], 
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])


subarray2 = array1[1:3, 2:4]

print("Last two Rows and Columns: \n",subarray2)

Last two Rows and Columns: 
 [[13 15]
 [ 6  8]]


### Boolean Indexing 

In [132]:
mask = arr > 3 # Creates boolean mask
mask

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False],
       [ True,  True,  True]])

In [134]:
arr[mask] # get elements where mask is true

array([4, 5, 6, 4, 5, 6])

In [139]:
mask = (arr > 3) & (arr < 7)
arr[mask] # combined conditions

array([4, 5, 6, 4, 5, 6])

### Broadcasting 

In [142]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])
result = arr1 + arr2
result

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

### Linear Algebra

In [148]:
random_arr

array([[0.57154018, 0.33893571, 0.51580685],
       [0.54804861, 0.85189646, 0.0197984 ],
       [0.44811626, 0.64675285, 0.83098652]])

In [150]:
np.linalg.inv(random_arr) # Inverse Matrix

array([[ 2.99807588,  0.2240591 , -1.86629272],
       [-1.92600917,  1.05153623,  1.17045219],
       [-0.1177331 , -0.93923134,  1.29884516]])

In [152]:
np.linalg.det(random_arr) # matrix determinant

0.23185197297542073

In [154]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
# a = 1x + 2y = 1 
# b = 3x + 5y = 2
np.linalg.solve(a, b) # Solve matrix linear equations

array([-1.,  1.])

## Statistics

In [157]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [4, 5, 6]])

In [158]:
np.median(arr)

3.5

In [161]:
np.percentile(arr, 75) # 75th percentile

5.0

In [163]:
np.corrcoef(a, b) # correlation coefficient

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [165]:
np.cov(a, b) # Covariance

array([[0.5, 1. , 0.5],
       [1. , 2. , 1. ],
       [0.5, 1. , 0.5]])

### Advanced Array Operations 

In [174]:
a = np.array([(1,2,3), (4,5,6)], dtype = int)
b = np.array([(7,8,9), (10,11,12)], dtype = int)
np.concatenate((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [177]:
np.vstack((b, a)) # vertical stack

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [179]:
np.hstack((b, a)) # horizontal stack

array([[ 7,  8,  9,  1,  2,  3],
       [10, 11, 12,  4,  5,  6]])

In [186]:
np.split(a, 2) # Split array into 2 parts

[array([[1, 2, 3]]), array([[4, 5, 6]])]

### Structured Arrays

In [187]:
dt = np.dtype([('name', 'U10'), ('age', 'i4')])
dt

dtype([('name', '<U10'), ('age', '<i4')])

In [189]:
struct_arr = np.array([('John', 25), ('Jane', 30)], dtype=dt)
struct_arr

array([('John', 25), ('Jane', 30)],
      dtype=[('name', '<U10'), ('age', '<i4')])

### Memory views

In [191]:
arr.flags # Memory layout information

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [193]:
arr.strides # Tuple of bytes to step in each dimension

(24, 8)

### Universal Functions 

In [195]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1],
       [4, 5, 6]])

In [196]:
np.add.reduce(arr) # Sum all elements column wise

array([12, 14, 16])

In [198]:
np.multiply.accumulate(arr)  # Running product 

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 12,  20,  18],
       [ 48, 100, 108]])

### Optimization

In [200]:
arr = np.vectorize(lambda x: x**2)(arr)
arr

array([[ 1,  4,  9],
       [16, 25, 36],
       [ 9,  4,  1],
       [16, 25, 36]])